pythonProject/mysite/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('home/', views.home, name = 'home'),
]

pythonProject/mysite/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
from . import views as login_views

urlpatterns = [
	path('login/', login_views.login_root, name='login_root'),
	path('login/success/', login_views.login_success, name='login_success'),
	path('login/fail/', login_views.login_fail, name='login_fail')
]

pythonProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'admin'


urlpatterns = [
    path('', include('home.urls')),
    path('products/', include('product.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls, name = 'admin'),
    path('api/', include('webLab.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginClass.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('accounts/password_reset/', views.PasswordResetView_.as_view(), name='password_reset'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView_.as_view(), name='password_reset_confirm'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView_.as_view(), name='password_reset_done'),
    path('accounts/reset/done/', views.PasswordResetCompleteView_.as_view(), name='password_reset_complete'),
    path('accounts/password_change/', views.PasswordChangeView_.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChageDoneView_.as_view(), name='password_change_done'),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    #path('profile/', views.user_profile, name='user_profile'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('logout', views.user_logout, name='logout')
]

pythonProject/mysite/login/models.py
from django.db import models

# Create your models here.

pythonProject/mysite/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


"""
class User(AbstractUser):
    Users within the Django authentication system are represented by this
    model.
    Username and password are required. Other fields are optional.
"""


class UserInfo(models.Model):
    # the relationship between class UserInfo and class User is one-to-one
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Info")

    user_fullname = models.CharField(max_length=30, blank=False, null=True)

    # user_description is required
    user_description = models.TextField(max_length=218, blank=False, null=True)
    # user_avatar is not required
    user_avatar = models.ImageField(upload_to='user_avatar', default='user_avatar/default-avatar.png', blank=True, null=True)

    def __str__(self):
        return self.user.username

# Create UserInfo if not created
User.Info = property(lambda u: UserInfo.objects.get_or_create(user=u)[0])

pythonProject/mysite/user/forms.py
from django import forms
from .models import UserInfo
from django.contrib.auth.models import User
from django.db import models
from django.core.files.images import get_image_dimensions

'''widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Username'})'''
class UserForm(forms.Form):
    username = forms.CharField(label='Username', min_length=6, max_length=150, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm'}))

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        #if r.count():
         #   raise forms.ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Those passwords didn't match. Try again.")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user


class UserInfoForm(forms.ModelForm):

    class Meta:
        model = UserInfo
        fields = ('user_fullname', 'user_description', 'user_avatar')
        widgets = {
            'user_fullname' : forms.TextInput(attrs={'class': 'form-control'}),
            'user_description' : forms.Textarea(attrs={'class': 'form-control', 'rows':'5'}),
            'user_avatar' : forms.FileInput(),
        }

pythonProject/mysite/login/views.py
from django.shortcuts import render


# Create your views here.

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate

def login_root(request):
	# Login form submitted?
	if request.method == 'POST':
		username=request.POST.get('username')
		password=request.POST.get('password')

		if username and password:
			user = authenticate(username=username, password=password)

			# Login succeeded
			if user is not None:
				url = reverse(viewname="login:login_success", current_app="login")

				return HttpResponseRedirect(url)

		# Login failed
		url = reverse(viewname="login:login_fail", current_app="login")
		return HttpResponseRedirect(url)

	return render(request, 'login/login_root.html')

def login_success(request):
	return render(request, 'login/login_success.html')

def login_fail(request):
	return render(request, 'login/login_fail.html')

pythonProject/mysite/user/views.py
from django.shortcuts import render, redirect
from user.forms import UserInfoForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import View
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.models import User
from .tokens import account_activation_token
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
#from task.views import make_noti
#from task.models import Task, Project, Notification
import sys
sys.path.append('../')
from product.models import Profile


class IndexView(View):
    def get(self, request):
        return render(request, 'user/index.html')

class HelpView(View):
    def get(self, request):
        return render(request, 'user/help.html')

class AuthorsView(View):
    def get(self, request):
        return render(request, 'user/authors.html')


@login_required
def user_logout(request):
    logout(request)
    request.session.flush()
    return redirect('home:home')

'''
@login_required(login_url='/login/')
def user_profile(request):
    # Add notification to navbar
    #make_noti(request)
    projects = request.user.project_set.all()
    tasks = Task.objects.filter(project__in = list(projects))
    notis = Notification.objects.filter(task__in = list(tasks)).order_by('-id')
    notic_count = len(list(Notification.objects.filter(actived = False)))
    
    # Form edit profile
    form = UserInfoForm(instance=request.user.Info)
    
    data = {"notis": notis, 'form': form, "notic_count": notic_count}
    
    if request.method == "POST":
        form = UserInfoForm(request.POST, request.FILES, instance=request.user.Info)
        if form.is_valid():
            custom_form = form.save(False)
            custom_form.user = request.user
            custom_form.save()
            return redirect('user:user_profile')
        
    return render(request, 'user/user_profile.html', data)
'''
class SignupView(View):
    """
    Load signup page
    If success == 1 then return successful registration message
    else return registration form
    """
    def get(self, request):
        user_form = UserForm()
        return render(request, 'user/signup.html', {'user_form': user_form, 'success': 0})

    def post(self, request):
        user_form = UserForm(request.POST)
        if user_form.is_valid():

            user = user_form.save(commit=False)
            user.is_active = True
            user.save()

            #profile = Profile.objects.create(user = user)
            #profile.save()
            return render(request, 'user/signup.html', {'user_form': user_form, 'success': 1,})
        return render(request, 'user/signup.html', {'user_form': user_form, 'success': 0, })


class LoginClass(View):
    """
    Load login page
    If user is authenticated then redirect to task:projects page
    else return the corresponding errors
    - Password is not correct
    - Account is inactive
    - Username does not exist
    """
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home:home')
        return render(request, 'user/login.html', {'mode': 0})

    def post(self, request):
        user_name = request.POST.get('username')
        pass_word = request.POST.get('password')
        # return a user if both username and password are valid

        user = authenticate(username=user_name, password=pass_word)
        if user:
            if user.is_active or True:
                login(request, user)
                return redirect('home:home')
        else:
            user = User.objects.filter(username=user_name)
            return render(request, 'user/login.html', {'user': user, 'mode': 1})


class ActivateView(View):

    def get(self, request, uidb64, token):
        try:
            # Decode a base64 encoded string. The received data is a user's primary key
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        # if user exists and check_token is correct then account is successful activated
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('home:home')
        else:
            return render(request, 'registrations/acc_active_invalid.html')


class PasswordChangeView_(auth_views.PasswordChangeView):
    success_url = reverse_lazy('user:password_change_done')
    template_name = 'registrations/password_change_form.html'


class PasswordChageDoneView_(auth_views.PasswordChangeDoneView):
    template_name = 'registrations/password_change_done.html'


class PasswordResetView_(auth_views.PasswordResetView):
    subject_template_name = 'registrations/password_reset_subject.txt'
    template_name = 'registrations/password_reset_form.html'
    success_url = reverse_lazy('user:password_reset_done')
    email_template_name = 'registrations/password_reset_email.html'
    html_email_template_name = email_template_name


class PasswordResetDoneView_(auth_views.PasswordResetDoneView):
    template_name = 'registrations/password_reset_done.html'


class PasswordResetConfirmView_(auth_views.PasswordResetConfirmView):
    template_name = 'registrations/password_reset_confirm.html'
    success_url = reverse_lazy('user:password_reset_complete')


class PasswordResetCompleteView_(auth_views.PasswordResetCompleteView):
    template_name = 'registrations/password_reset_complete.html'

pythonProject/mysite/user/templates/user/authors.html
{% extends "user/base.html" %}
{% block title%}About us{% endblock %}
{% block content %}
<div class="container" style="padding-top: 20vh">
  <div class="row">
	  <div class="col-md-10 col-sm-6">
		  <div class="about-title clearfix">
				<h1>Thank you for visiting!</h1>
				<hr>
				<h2 style="color:red;">What is <span>Up-to-date?</span></h2>
				<h6>Up-to-date is a free and effective work management tool for individuals, helping you plan and manage time, streamline work, avoid stress, and always " flooded "during the deadline.</h6>
				<h3>Who are we?</h3>
				<h5>We are freshmen at Bauman Moscow State Technical University.</h5>
				<ul>
					<li>Ayjahan Meredova</li>
					<li>Pham Quang Anh</li>
					<li>Nguyen Phuoc Sang</li>
					<li>Gissane Tovmasyan</li>
					<li>Vo Dai Hoang Phuc</li>
				</ul>
				<h5>This is our first project about Web application.</h5>
        <p>Email : uptodate.iu.26b@gmail.com</p>
			</div>
		</div>
  </div>
</div>

{% endblock %}

pythonProject/mysite/user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}"> <!--load all styles -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <style>
        .carousel-item {
            height: 100vh;
            min-height: 350px;
            background: no-repeat center center scroll;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .centered {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            }

        p {
            color: #4D8096;
        }

    </style>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% csrf_token %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
       <div class="navbar-brand">
           <a class="nav-link" style="color:black" href="{% url 'user:index' %}">K-Travel</a>
       </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login'%}">Log in</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:signup'%}">Sign up</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:help'%}">Help</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:authors'%}">About us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

pythonProject/mysite/user/templates/user/help.html
{% extends "user/base.html" %}
{% block title %}Help{% endblock %}
{% block content %}
{% endblock %}

pythonProject/mysite/user/templates/user/index.html
{% extends "user/base.html" %}
{% load static %}
{% block title%}Up to Date{% endblock %}
{% block content %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active" style="background-image: url('{% static 'image/img1.jpg'%}')">
        <div class="centered">
            <p style="font-size: 6em; font-family:freestyle script">Organize your tasks easier</p>
            <p style="font-size: 1.4em;">Using our cards allows you</p>
            <p style="font-size: 1.4em;">to organize and prioritize your projects in a flexible way.</p>
        </div>
    </div>
    <div class="carousel-item" style="background-image: url('{% static 'image/img2.jpg'%}')">
        <div class="centered">
            <p style="font-size: 6em; font-family:freestyle script">Work more productive</p>
            <p style="font-size: 1.4em;">With us your projects are always under control.</p>
            <p style="font-size: 1.4em;">Never worry about missing anything.</p>
        </div>
    </div>
    <div class="carousel-item" style="  background-image: url('{% static 'image/img3.jpg'%}')"> </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

{% endblock %}

pythonProject/mysite/user/templates/user/login.html
{% extends "user/base.html" %}
{% block tittle %}Log in{% endblock %}
{% block content %}
<div class="container" style="margin-top:8%; padding:0% 15%" >
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
        <h1 class="card-title mt-3 text-center" style="color: #4D8096; font-size: 5em; font-family:freestyle script">Log in</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group input-group">
		        <div class="input-group-prepend">
		            <span class="input-group-text"><i style="color: #4D8096" class="fa fa-user"></i></span>
                </div>
                <input class="form-control" type="text" name="username" placeholder="Username" required>
            </div>
            <div class="form-group input-group">
		        <div class="input-group-prepend">
		            <div class="input-group-text"><i style="color: #4D8096" class="fa fa-lock"></i></div>
                </div>
                <input class="form-control" type="password" name="password" placeholder="Password" required>
            </div>
            {% if mode %}
                {% if user.count %}
                {% for userr in user %}
                    {% if userr.is_active %}
                    <p style="color: #4D8096">Password is incorrect</p>
                    {% else %}
                    <p style="color: #4D8096">Account is inactive</p>
                    {% endif %}
                {% endfor%}
                {% else %}
                <p style="color: #4D8096">Username does not exist</p>
                {% endif %}
            {% endif %}
            <div class="form-group">
            <button type="submit" name = "submit" class="btn btn-block" style="background-color:#4D8096; color:white">Log in</button>
            </div>
        <p class="text-center">Don't have an account? <a href="../signup/">Sign up</a> </p>
        <p class="text-center">Forgot your password? <a href="{% url 'user:password_reset'%}">Click here</a> </p>
        </form>
        </article>
    </div>
</div>
{% endblock %}

pythonProject/mysite/user/templates/user/signup.html
{% extends "user/base.html" %}
{% block title%}Sign up{% endblock%}
{% block content %}
<div class="container" style="margin-top:8%; padding:0% 15%" >
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
        <h2 class="card-title mt-3 text-center" style="color: #4D8096; font-size: 5em; font-family:freestyle script">Registration</h2>
        <form method="POST">
        {% csrf_token %}
        {% if success %}
            <h2 class="mt-3 text-center" style="color: #4D8096; font-size: 1.5em; font-family:times new roman">
                Sinup Succesful. Click <a href="{% url 'user:login' %}">Here</a> to Go to Login
            </h2>
        {% else %}
            {% for field in user_form %}
            <div class="form-group input-group">
		    <div class="input-group-prepend">
		        <span style="color: #4D8096"  class="input-group-text">
                    {% if field.name == "username" %}
                        <i class="fa fa-user"></i>
                    {% elif field.name == "email" %}
                        <i class="fa fa-envelope"></i>
                    {% elif field.name == "password1" %}
                        <i class="fa fa-lock"></i>
                    {% elif field.name == "password2" %}
                        <i class="fa fa-lock"></i>
                    {% endif %}
                </span>
            </div>
            {{ field }}
            </div>
            {% for error in field.errors %}
            <p style="color: #4D8096">{{ error }}</p>
            {% endfor %}
            {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-block" style="background-color:#4D8096; color:white">Create Account</button>
            </div>
            <p class="text-center">Have an account? <a href="../login/">Log In</a> </p>
        {% endif %}
        </form>
        </article>
    </div>
</div>
{% endblock %}

pythonProject/mysite/user/templates/user/user_profile.html
{% extends "task/base.html" %}
{% load staticfiles %}
{% block title %}Up-to-date{% endblock %}

{% block contain %}
<!--Information-->
  <div class="jumbotron" style="margin-top: 80px">
    <form method="POST" action="{% url 'user:user_profile'%}" enctype="multipart/form-data">{% csrf_token %}
      <div class="row">
        <!--Avatar form-->
        <div class="col-sm-3">
          <div class="text-center">
            <img src="{{user.Info.user_avatar.url}}" width="200" height="200" class="rounded-circle" alt="avatar"></img>
            <p class="py-1" data-toggle="collapse" data-target="#collapseForm">
              <label for="id_user_avatar" class="custom-file-upload">Upload image</label>
              {{form.user_avatar}}
            </p>
          </div>
        </div>
        <!--End avatar form-->
        <!--Info form-->
        <div class="col-lg-8">
          <div class="container">
            {% if user.Info.user_fullname %}
              <h4 class="display-4">{{user.Info.user_fullname}}</h4>
              <p style="word-break: break-word">{{user.Info.user_description}}</p>
            {% else %}
              <h4 class="display-4">{{user.username}}</h4>
            {% endif %}
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseForm" aria-expanded="false" aria-controls="collapseForm" style="background-color: #4d8096">
              Edit profile »
            </button>
          </div>
        <br><br>
        <div class="collapse" id="collapseForm" data-toggle="collapse">
          <div class="form-group">
            <label for="id_user_fullname">Full Name</label>
            {{form.user_fullname}}
          </div>
          <div class="form-group">
            <label for="id_user_description">Description</label>
            {{form.user_description}}
          </div>
          <button type="submit" class="btn btn-primary">Save</button>
          <span></span>
          <button type="reset" class="btn btn-info" data-toggle="collapse" data-target="#collapseForm" style="background-color: #4d8096">Cancel</button>
        </div>
        </div>
      </div>
    </form>
  </div>
  <!--Container-->
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-lg-8 pb-5">
        <a href="{% url 'user:password_change' %}">Change you password</a>
      </div>
    </div>
  </div>
 <!-- /container -->
  <script>
    $('#id_user_avatar').change(function() {
      var i = $(this).prev('label').clone();
      var file = $('#id_user_avatar')[0].files[0].name.slice(-10,);
      $(this).prev('label').text(file);
    });
  </script>
{% endblock %}