pythonProject/mysite/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('home/', views.home, name = 'home'),
]

pythonProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'admin'


urlpatterns = [
    path('', include('home.urls')),
    path('products/', include('product.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls, name = 'admin'),
    path('api/', include('webLab.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('product=<int:id>/', views.showProduct, name = 'product'),
    path('search=<str:name>/', views.search, name = 'search'),
    path('contact/', views.showContact, name = 'contact'),
    path('profile/', views.editProfile, name = 'profile'),
    path('Type=<str:type>&Order=<str:order>&Filter=<str:filter>/', views.showAllProduct, name='type_order_filter'),
    path('Type=<str:type>&Filter=<str:filter>/', views.showAllProduct, name='type_filter'),
    path('Type=<str:type>&Order=<str:order>/', views.showAllProduct, name='type_order'),
    path('Type=<str:type>/', views.showAllProduct, name='type'),
    path('<str:str>/', views.show, name='show'),

]

pythonProject/mysite/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginClass.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('accounts/password_reset/', views.PasswordResetView_.as_view(), name='password_reset'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView_.as_view(), name='password_reset_confirm'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView_.as_view(), name='password_reset_done'),
    path('accounts/reset/done/', views.PasswordResetCompleteView_.as_view(), name='password_reset_complete'),
    path('accounts/password_change/', views.PasswordChangeView_.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChageDoneView_.as_view(), name='password_change_done'),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    #path('profile/', views.user_profile, name='user_profile'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('logout', views.user_logout, name='logout')
]

pythonProject/mysite/home/models.py
from django.db import models

# Create your models here.

pythonProject/mysite/home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'home/home.html')

pythonProject/mysite/home/templates/home/home.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css'%}">


  <title>K-Travel</title>

</head>

<body>



	<section class = "Slider">
		<div class = "aspect-ratio-169">
			<img src="{% static 'image/font1.jpg'%}">
			<img src="{% static 'image/font2.jpg'%}">
			<img src="{% static 'image/font3.jpg'%}">
			<img src="{% static 'image/font4.jpg'%}">
			<img src="{% static 'image/font5.jpg'%}">
	</div>

	<div class = "dot-container">
		<div class = "dot active"></div>
		<div class = "dot"></div>
		<div class = "dot"></div>
		<div class = "dot"></div>
		<div class = "dot"></div>
	</div>
	</section>

		<div class="">
		<nav class="navbar navbar-inverse navbar-static-top navbar-fixed-top">
			<div class="container">
				<div class="navbar-header ">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
		                <span class="sr-only">Toggle navigation</span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		            </button>
		            <a href="{% url 'home:home' %}" class="navbar-brand ">K-Travel</a>
				</div>

				<div class="navbar-collapse collapse" id="menu">
			        <ul class="nav navbar-nav navbar-right">
				        <li class=""><a href="{% url 'product:type' 'All'%}"><span class="glyphicon glyphicon-home"></span> All</a></li>
				        <li><a href="{% url 'product:type' 'Sight' %}"><span class="glyphicon glyphicon-home"></span> Sight</a></li>
				        <li><a href="{% url 'product:type' 'Restauran' %}"><span class="glyphicon glyphicon-home"></span> Restauran</a></li>
				        <li><a href="{% url 'product:type' 'Museum'%}"><span class="glyphicon glyphicon-home"></span> Museum</a></li>
				        <li><a href=""><span class="glyphicon glyphicon-user"></span> Contact</a></li>
				        <li class="dropdown">
			                <a data-toggle="dropdown" href=""><span class="glyphicon glyphicon-user"></span> Account<span class="caret"></span></a>
			                <ul class="dropdown-menu">
								{% if user.is_authenticated %}
									<li><a href="{% url 'product:profile' %}">Profile</a></li>
									<li><a href="{% url 'user:password_change' %}">Change Password</a></li>
									<div class="divider"></div>
									<li><a href="{%  url 'user:logout' %}">Logout</a></li>
								{% else %}
									<li>
										<a href="{% url 'user:login' %}">Login</a>
									</li>
								{% endif %}
			                </ul>
			            </li>
			        </ul>
			        <form action="" class="navbar-form " method="post">
				        <div class="form-group">
				            <input type="text" class="form-control" placeholder="Search Place">
				        </div>
				    </form>
			    </div>

			</div>
		</nav>
	</div>


	<div class = "footer-top">

		<li><a href=""> Liên Hệ</a></li>
		<li><a href=""> Giới Thiệu</a></li>
		<li>
			<a href="" class = "fab fa-facebook-f"></a>
		</li>
	</div>

	<div class = "footer-bottom">
		@NguyenPhuocSang
	</div>




<script type="text/javascript">
	const imgPosition = document.querySelectorAll(".aspect-ratio-169 img");
	const imgContainer = document.querySelector(".aspect-ratio-169")

	const dotItem = document.querySelectorAll(".dot")
	let index = 0;
	imgNumber = imgPosition.length

	imgPosition.forEach(function(image, index){
		image.style.left = index*100+ "%"
		dotItem[index].addEventListener("click", function(){
			slider(index);
		})
	})

	function imgSlide(){
		index++;
		if (index >= imgNumber) {index = 0;}
		slider(index);
		}

	function slider(index){
		imgContainer.style.left = "-" + index * 100 + "%";
		const dotActive = document.querySelector(".active");
		dotActive.classList.remove("active");
		dotItem[index].classList.add("active");
	}
	setInterval(imgSlide, 3000);

</script>

</body>
</html>