pythonProject/mysite/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('home/', views.home, name = 'home'),
]

pythonProject/mysite/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
from . import views as login_views

urlpatterns = [
	path('login/', login_views.login_root, name='login_root'),
	path('login/success/', login_views.login_success, name='login_success'),
	path('login/fail/', login_views.login_fail, name='login_fail')
]

pythonProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'admin'


urlpatterns = [
    path('', include('home.urls')),
    path('products/', include('product.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls, name = 'admin'),
    path('api/', include('webLab.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('product=<int:id>/', views.showProduct, name = 'product'),
    path('search=<str:name>/', views.search, name = 'search'),
    path('contact/', views.showContact, name = 'contact'),
    path('profile/', views.editProfile, name = 'profile'),
    path('Type=<str:type>&Order=<str:order>&Filter=<str:filter>/', views.showAllProduct, name='type_order_filter'),
    path('Type=<str:type>&Filter=<str:filter>/', views.showAllProduct, name='type_filter'),
    path('Type=<str:type>&Order=<str:order>/', views.showAllProduct, name='type_order'),
    path('Type=<str:type>/', views.showAllProduct, name='type'),
    path('<str:str>/', views.show, name='show'),

]

pythonProject/mysite/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginClass.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('accounts/password_reset/', views.PasswordResetView_.as_view(), name='password_reset'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView_.as_view(), name='password_reset_confirm'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView_.as_view(), name='password_reset_done'),
    path('accounts/reset/done/', views.PasswordResetCompleteView_.as_view(), name='password_reset_complete'),
    path('accounts/password_change/', views.PasswordChangeView_.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChageDoneView_.as_view(), name='password_change_done'),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    #path('profile/', views.user_profile, name='user_profile'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('logout', views.user_logout, name='logout')
]

pythonProject/mysite/login/models.py
from django.db import models

# Create your models here.

pythonProject/mysite/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from django.core.validators import MaxValueValidator, MinValueValidator


from django.dispatch import receiver #add this
from django.db.models.signals import post_save #add this


# Create your models here.

class City(models.Model):
    Name = models.CharField(max_length= 30, )

    def __str__(self):
        return self.Name



class Place(models.Model):

    Name = models.CharField(max_length= 100, default=' ')
    City = models.ForeignKey(City, on_delete= models.CASCADE, default= 1)
    Rating = models.DecimalField(default= 0.0, max_digits= 3, decimal_places=1)
    Address = models.CharField(max_length= 100, default= '')
    Description = models.TextField(default='')
    Type = models.IntegerField(default= 1)
    Site = models.CharField(max_length= 100, default='')
    Tel = models.CharField(max_length=20, default='')

    models.UniqueConstraint(fields= ['Name'], name = 'Unique_Place')

    def __str__(self):
        return self.Name

    def getImg(self):
        imgs = self.img_set.all()
        #urls = [item.url for item in imgs]
        return imgs

    def getFirstImg(self):
        #img = self.img_set.all()[0]
        img = Img.objects.all().filter(place = self.id)[0]
        return img

    def getReview(self):
        return Review.objects.all().filter(place = self.id)

    def getRating(self):
        reviews = self.getReview()
        sum = 0
        n = len(reviews)
        if (n == 0):
            return 0

        for item in reviews:
            sum = sum + item.rating
        rating = round(sum / n, 1)
        self.Rating = rating
        #self.save()
        return rating

    def updateRating(self):
        self.Rating = self.getRating()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(null=True, default='./icon-login.png')

    def __str__(self):
        return self.user.username


def createProfile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.created(user=kwargs['instance'])
        post_save.connect(createProfile, sender=User)

class Review(models.Model):
    comment = models.CharField(max_length=1000)
    createTime = models.DateTimeField(timezone.datetime.now())
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    auth = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0,
        validators= [MaxValueValidator(5),
                     MinValueValidator(0),]
                                 )
    def __str__(self):
        return self.comment

class Img(models.Model):
    img = models.ImageField(null=True)
    name = models.CharField(max_length=100, null=True, default= '')
    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

pythonProject/mysite/product/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile

from .models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
        )
        widgets = {
            'username': forms.TextInput(attrs = {'class': "form-control"}),
            'email': forms.EmailInput(attrs = {"class": "form-control"}),
            'first_name': forms.TextInput(attrs={"class": "form-control"}),
            'last_name': forms.TextInput(attrs={"class": "form-control"}),

        }

        def clean_username(self):
            username = self.cleaned_data['username'].lower()
            r = User.objects.filter(username=username)
            if r.count():
                raise forms.ValidationError("Username already exists")
            return username

        def clean_email(self):
            email = self.cleaned_data['email'].lower()
            r = User.objects.filter(email=email)
            # if r.count():
            #   raise forms.ValidationError("Email already exists")
            return email


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'avatar',
        )

        widgets = {
            'avatar' : forms.FileInput(attrs = {'onchange': 'loadFile (event)',})
        }

class SearchForm(forms.Form):
    search = forms.CharField(max_length= 30, widget=forms.TextInput(attrs = {'class' : "form-control", 'id': "search", 'placeholder' : "Search Place"}))

class ReviewForm(forms.Form):
    comment = forms.CharField(max_length= 100, widget = forms.Textarea(attrs={'class':"form-control",'placeholder':"write a comment...",'rows':"3"}))
    rating = forms.IntegerField(max_value=5)

pythonProject/mysite/login/views.py
from django.shortcuts import render


# Create your views here.

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate

def login_root(request):
	# Login form submitted?
	if request.method == 'POST':
		username=request.POST.get('username')
		password=request.POST.get('password')

		if username and password:
			user = authenticate(username=username, password=password)

			# Login succeeded
			if user is not None:
				url = reverse(viewname="login:login_success", current_app="login")

				return HttpResponseRedirect(url)

		# Login failed
		url = reverse(viewname="login:login_fail", current_app="login")
		return HttpResponseRedirect(url)

	return render(request, 'login/login_root.html')

def login_success(request):
	return render(request, 'login/login_success.html')

def login_fail(request):
	return render(request, 'login/login_fail.html')

pythonProject/mysite/product/views.py
from django.shortcuts import render, redirect
from django.http import  HttpResponse
from .models import Place, Img, Review, Profile, City
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ProfileForm, SearchForm, ReviewForm
from django.utils import timezone
from django.views import View

from django.contrib.auth import update_session_auth_hash


# Create your views here.

def index(request):
    return HttpResponse("Hello World")

def findStr(filter, str):
    if (filter == None or str == None):
        return None
    else:
        res = None
        i1 = filter.rfind(str)
        if (i1 >= 0):
            t = i1 + len(str)
            tmp = filter.find('&', t + 1)
            if (tmp == -1):
                res = filter[t:]
            else:
                res = filter[t:tmp]
        return res


class ShowAllProduct(View):
    def get(self, request):
        pass
def showAllProduct(request, type = None, order = None, filter = None):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']
            place_list = Place.objects.all().filter(Name__contains=data)
            title = 'Search: {}'.format(str)
            context = {'place_list': place_list, 'title': title, 'searchForm': SearchForm()}
            return redirect('product:search', name = data)

    place_list = Place.objects.all()
    title = 'All'

    if (type == 'Sight'):
        place_list = place_list.filter(Type = 1)
        title = type
    elif (type == 'Restauran'):
        place_list = place_list.filter(Type = 2)
        title = type
    elif (type == 'Museum'):
        place_list = place_list.filter(Type = 3)
        title = type

    print(order)
    if (order == 'rating'):
        place_list = place_list.order_by('-Rating')
    elif (order == 'name'):
        place_list = place_list.order_by('Name')

    if (filter != None):
        try:
            c = City.objects.get(Name = filter)
            place_list = place_list.filter(City = c.id)
        except:
            print("Error")


    searchForm = SearchForm()
    allCity = City.objects.all()
    content = {'place_list': place_list, 'title': title, 'searchForm': searchForm, 'allCity': allCity}
    return render(request, 'product/cartegory.html', content)


def showProduct(request, id):
    p = Place.objects.get(id = id)
    p.updateRating()
    img5 = Img.objects.all().filter(place = id)[0:5]
    relatedProduct = Place.objects.exclude(id = id)[0:5]

    if request.user.is_authenticated:
        a = request.user.id
        try:
            userReview = Review.objects.get(id =  request.user.id)
        except:
            userReview = []
    try:
        reviews  = Review.objects.filter(place = id)
    except:
        reviews = []
    r = []
    for i in reviews:
        r.append([Profile.objects.get(user = i.auth), i])

    searchForm = SearchForm()
    reviewForm = ReviewForm()
    print('CHECK GET METHOD')

    if request.method == 'POST':
        print("Enter POST")

        reviewForm = ReviewForm(request.POST)
        if reviewForm.is_valid():
            comment = reviewForm.cleaned_data['comment']
            rating = reviewForm.cleaned_data['rating']
            print(rating)
            print(comment,  id, request.user.id)
            newReview = Review.objects.create(comment = comment, createTime = timezone.datetime.now(),
                                              place = Place.objects.get(id = id), auth = request.user, rating = rating)
            newReview.save()
            return redirect('product:product', id = id)



    content = {'place': p, 'img5': img5, 'related': relatedProduct, 'auth': r, 'searchForm' : SearchForm(), 'reviewForm': reviewForm}

    return render(request, 'product/product.html', content)

'''
User
'''

def login(request):
    return render(request, 'product/login.html')

@login_required(login_url='/products/login/')
def profile(request):
    if request.user.is_authenticated:
        cur_user = request.user
        try:
            p = Profile.objects.get(user = cur_user)
            context = {'profile': p}
            return render(request, 'product/profile.html', context)
        except:
            redirect('admin:admin')
    else:
        return redirect('product:login')

@login_required(login_url='/products/login/')
def editProfile(request):
    if (request.method == 'POST'):
        userform = UserForm(request.POST, instance=request.user)
        profileform = ProfileForm(request.POST, request.FILES, request.user.profile)

        if userform.is_valid() and profileform.is_valid():

            p = Profile.objects.get(user=request.user)
            ava = p.avatar
            p.delete()
            user_form = userform.save()
            Profile.objects.get(user = request.user).delete()
            profile_form = profileform.save(False)
            profile_form.user = request.user
            if (not request.FILES):
                profile_form.avatar = ava
            profile_form.save()
        return redirect('product:profile')
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=request.user.profile)
        args = {}
        args['userform'] = userform
        args['profileform'] = profileform
        args['profile'] = request.user.profile
        return render(request, 'product/profile.html', args)



def search(request, name):
    place_list = Place.objects.all().filter(Name__contains = name)
    title = 'Search: {}'.format(name)
    searchForm = SearchForm()
    context = {'place_list': place_list, 'title': title, 'searchForm': searchForm}
    return render(request, 'product/cartegory.html', context)


def show(request, str):
    type = findStr(str, 'Type=')
    order = findStr(str, 'Order=')
    city = findStr(str, 'City=')
    filter = findStr(str, 'Filter=')
    return redirect('product:type_order_filter', type = type, order = order, filter = filter)


def showContact(request):
    return render(request, 'product/contact.html')

pythonProject/mysite/product/templates/product/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


  <title>K-Travel</title>

</head>

<body>

		{% block content %}

		{% endblock %}


	<div class="" >
		<nav class="navbar navbar-inverse navbar-static-top navbar-fixed-top">
			<div class="container" style="">
				<div class="navbar-header ">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
		                <span class="sr-only">Toggle navigation</span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		            </button>
		            <a href="{% url 'home:home' %}" class="navbar-brand ">K-Travel</a>
				</div>

				<div class="navbar-collapse collapse" id="menu">
			        <ul class="nav navbar-nav navbar-right">
				        <li class=""><a href="{% url 'product:type' 'All'%}"><span class="glyphicon glyphicon-home" ></span> All</a></li>
				        <li><a href="{% url 'product:type' 'Sight' %}"><span class="glyphicon glyphicon-home"></span> Sight</a></li>
				        <li><a href="{% url 'product:type' 'Restauran' %}"><span class="glyphicon glyphicon-home"></span> Restauran</a></li>
				        <li><a href="{% url 'product:type' 'Museum'%}"><span class="glyphicon glyphicon-home"></span> Museum</a></li>
				        <li><a href="{% url 'product:contact' %}"><span class="glyphicon glyphicon-user"></span> Contact</a></li>
				        <li class="dropdown">
			                <a data-toggle="dropdown" href=""><span class="glyphicon glyphicon-user"></span> Account<span class="caret"></span></a>
			                <ul class="dropdown-menu">
								{% if user.is_authenticated %}
									<li><a href="{% url 'product:profile' %}">Profile</a></li>
									<li><a href="{% url 'user:password_change' %}">Change Password</a></li>
									<div class="divider"></div>
									<li><a href="{%  url 'user:logout' %}">Logout</a></li>
								{% else %}
									<li>
										<a href="{% url 'user:login' %}">Login</a>
									</li>
								{% endif %}
			                </ul>
			            </li>
			        </ul>
			        <form action="{% url 'product:type' 'All' %}" class="navbar-form " method="post" name = 'searchForm'>
						{% csrf_token %}
				        <div class="form-group">
							{{ searchForm.search }}
				        </div>
				    </form>
			    </div>

			</div>
		</nav>
	</div>



	<section class = "footer">
	<div class = "footer-top">

		<li><a href="https://www.facebook.com/WeiYae"> Liên Hệ</a></li>
		<li><a href="https://www.facebook.com/WeiYae"> Giới Thiệu</a></li>
		<li>
			<a href="" class = "fab fa-facebook-f"></a>
		</li>
	</div>

	<div class = "footer-bottom">
		@NguyenPhuocSang
	</div>
</section>




<script type="text/javascript">

	window.onload = function() {
    }
	var currentLocation = window.location.href;

	const allImg = document.querySelectorAll("img")
	allImg.forEach(function(image, index){
		image.height =  image.width * 11 / 16;
	})




</script>

</body>
</html>

pythonProject/mysite/product/templates/product/cartegory.html
{% extends 'product/base.html' %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<section class = "cartegory">
		
		<div class="container">
			<div class="row">
				<div class = "cartegory-left">
				</div>

				<div class="row">
						<ul class="breadcrumb", style="">
								<li><a href="{% url 'home:home' %}">Home</a></li>
								{% if title ==  'Sight' %}
									<li><a href="{% url 'product:type' 'Sight' %}">Sight</a></li>
								{% else %}
									{% if title == 'Restauran' %}
										<li><a href="{% url 'product:type' 'Restauran' %}">Restauran</a></li>
									{% else %}
										{% if title == 'Museum' %}
											<li><a href="{% url 'product:type' 'Museum' %}">Museum</a></li>
										{% else %}
											<li><a href="{% url 'product:type' 'All' %}">All</a></li>
										{% endif %}
									{% endif%}
								{% endif%}

							</ul>
						<div class="cartegory-right-top-item">

						</div>
						<div class="cartegory-right-top-item">
							<select id="city-select">
								<option>City Filter</option>
								{% for city in allCity %}

								<option value="{{city.Name}}">{{ city.Name}}</option>
								{% endfor %}
							</select>
						</div>

						<div class="cartegory-right-top-item">
							<form>
							<select id = "sort-select" onchange="sortSelectFuntion()">
								<option value="auto">Sort</option>
								<option value="rating">Rating</option>
								<option value="name">Name</option>
							</select>
							</form>
						</div>
				</div>

					<div class="cartegory-right-content row">

						{% for place in place_list %}
							<div class="cartegory-right-content-item">
								<a href="{% url 'product:product' place.id %}">
								<img src="{{ place.getFirstImg.img.url }}" style="">
								<h1>{{ place.Name }} ( {{place.Rating}} <span class="fa fa-star checked"></span> )</h1>
								</a>
							</div>
						{% endfor %}




					</div>





			</div>
		</div>
		
	</section>

<script type="text/javascript">

document.getElementById("city-select").addEventListener('change', (event) => {
  	var data = event.target.value;
	var href = window.location.href.slice(0, -1);
	href = href.replace("/products/", "/products/abc");
	href = href+"&Filter="+data+'/';
	window.location.replace(href);
	});

document.getElementById("sort-select").addEventListener('change', (event) => {
  	var data = event.target.value;
	var href = window.location.href.slice(0, -1);
	href = href.replace("/products/", "/products/abc");
	href = href+"&Order="+data+'/';
	window.location.replace(href);
	});

</script>

{% endblock %}

pythonProject/mysite/product/templates/product/contact.html
{% extends 'product/base.html' %}
{% load static %}

{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

<div class="container">
    <div class="view-account">
        <section class="module">
            <div class="module-inner">
                <div class="side-bar">
                    <div class="user-info">
                        <img class="img-profile img-circle img-responsive center-block" src="{% static 'image/font1.jpg' %}" alt="">
                        <ul class="meta list list-unstyled">
                            <li class="name">Nguyen Phuoc Sang</li>
                            <li class="email"><a href="#">nguyensanghso@gmail.com</a></li>
                        </ul>
                    </div>

                </div>

            </div>
        </section>
    </div>
</div>
<script>


var loadFile = function (event) {
	var image = document.getElementById ('small-avatar');
	image.src = URL.createObjectURL (event.target.files [0]);
};
</script>

{% endblock %}

pythonProject/mysite/product/templates/product/login.html
{% extends 'product/base.html' %}

{% block content %}

<div class="container">
    <div class="row login_form">
        <h2 style="width:100%;">Login</h2>
        <form>
            <div class="form-group">
                <label>Email</label>
                <input type="email" class="form-control" placeholder="Email">
            </div>
            <div class="form-group">
                <label>Mật Khẩu</label>
                <input type="password" class="form-control" placeholder="Password">
            </div>
            <div class="checkbox">
                <label><input type="checkbox"> Ghi Nhớ</label>
            </div>
            <button type="submit" class="btn btn-primary">Đăng Nhập</button>
        </form>
    </div>
</div>

{% endblock %}

     

pythonProject/mysite/product/templates/product/product.html
{% extends 'product/base.html' %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<section class = "product">
		<div class="container">
            <div class="row">
                <ul class="breadcrumb">
                    <li><a href="{% url 'home:home' %}">Home</a></li>
					{% if place.Type ==  1 %}
						<li><a href="{% url 'product:type' 'Sight' %}">Sight</a></li>
					{% else %}
						{% if place.Type == 2 %}
							<li><a href="{% url 'product:type' 'Restauran' %}">Restauran</a></li>
						{% else %}
							<li><a href="{% url 'product:type' 'Museum' %}">Museum</a></li>
						{% endif%}
					{% endif%}

                    <li class="active">{{ place.Name }}</li>
                </ul>
            </div>

			<div class="product-content row">
				<div class="product-content-left row">
					<div class="product-content-left-big-img">
						<img src="{{ img5.0.img.url }}">

					</div>

					<div class="product-content-left-small-img">
						<img src="{{ img5.1.img.url }}">
						<img src="{{ img5.2.img.url }}">
						<img src="{{ img5.3.img.url }}">
						<img src="{{ img5.4.img.url }}">
					</div>
				
				</div>

				<div class="product-content-right">
					<div class="product-content-right-product-name">
						<h1>{{ place.Name }}</h1>
					</div>

					<div class="product-content-right-product-rating">
						<p>Rating {{ place.Rating }}/5</p>
					</div>

					<div class="product-content-right-bottom">

						<div class="product-content-right-bottom-container">
							<ul class="nav nav-tabs">
								<li><a href="#home" data-toggle="tab"> Description <span ></span></a></li>
								<li><a href="#lang-nha-bang" data-toggle="tab"> Information</a></li>
								<li><a href="#lang-nha-bang-2" data-toggle="tab"> Other</a></li>
								
							</ul>
							<div class="tab-content">
								<div class="tab-pane" id="home">{{ place.Description}}</div>
								<div class="tab-pane" id="lang-nha-bang">
									<div class = 'place-infor'>Address: {{ place.Adress }}</div>
									<div class = 'place-infor'>Telephone: {{ place.Tel }}</div>
									<div class = 'place-infor'>Website: <a href="{{ place.Site }}"> {{ place.Site }}</a></div>

								</div>
								<div class="tab-pane" id="lang-nha-bang-2"> LANG NHA BANG 2</div>

							</div>

						</div>

					</div>

					<div class=""></div>
				</div>

			</div>

			
		</div>
		
	</section>

	<section class="product-related">
		<div class="container">
			<div class="product-related-title">
				<p>Related </p>
			</div>

			<div class="product-related-content row">
				{% for product in related %}
				<div class="product-related-content-item">
					<a href="{% url 'product:product' product.id %}">
					<img src="{{product.getFirstImg.img.url}}">
					<h1>{{ product.Name }}</h1>
					</a>
				</div>
				{% endfor %}
			</div>

		</div>
		
	</section>

	<section class="product-comment">

		<div class="container">
			<div class="">
			    <div class="comment">
			        <div class="comment-wrapper">
			            <div class="panel panel-info">

			                <div class="panel-heading">
			                    Comment panel
			                </div>
			                <div class="panel-body">
								<form action="{% url 'product:product' place.id %}" class="navbar-form " method="post" name = 'commentForm' novalidate>
									{% csrf_token %}
									<div style="display: none">{{ reviewForm.rating }}</div>

									<div class = '' id = 'start-rating'>
										<span class="fa fa-star checked" id = '1rating'></span>
										<span class="fa fa-star checked" id = '2rating'></span>
										<span class="fa fa-star checked" id = '3rating'></span>
										<span class="fa fa-star checked" id = '4rating'></span>
										<span class="fa fa-star checked" id = '5rating'></span>
									</div>

									{{  reviewForm.comment }}
			                    <br>
									<input type="submit" class="btn btn-info pull-right" name="submit" value="Post" />
									</form>

			                    <div class="clearfix"></div>
			                    <hr>

			                    <ul class="media-list">
									{% for r in auth %}
									<li class="media">
			                            <a href="#" class="pull-left">
			                                <img src="{{r.0.avatar.url}}" alt="" class="img-circle">
			                            </a>
			                            <div class="media-body">
												<div class="rate pull-right show-rating rating{{r.1.rating}}">
												<span class="fa fa-star"></span>
												<span class="fa fa-star"></span>
												<span class="fa fa-star"></span>
												<span class="fa fa-star"></span>
												<span class="fa fa-star"></span>
												</div>
			                                <strong class="text-success">@ {{ r.0.user.username }}</strong>
			                                <p>
												{{ r.1.comment }}
			                                </p>
			                            </div>
			                        </li>
									{% endfor %}

			                    </ul>
			                </div>
			            </div>
			        </div>

			    </div>
			</div>
		</div>
		
	</section>

<script type="text/javascript">

	const handleStarSelect = (par, size) => {
		const children = par.children;
		for (let i = 0; i < children.length; i++){
			if (i <size) {
				children[i].classList.add("checked");
			}
			else {
				children[i].classList.remove("checked");
			}
		}
	}

	const a = document.getElementsByClassName("show-rating");
	for (let i = 0; i < a.length; i++)
	{
		item = a[i];
		if (item.classList.contains('rating1'))
		{
			handleStarSelect(item, 1);
		}
		if (item.classList.contains('rating2'))
		{
			handleStarSelect(item, 2);
		}
		if (item.classList.contains('rating3')) {
			handleStarSelect(item, 3);
		}
		if (item.classList.contains('rating4')) {
			handleStarSelect(item, 4);
		}
		if (item.classList.contains('rating5')) {
			handleStarSelect(item, 5);
		}
	}

	const handleSelect = (d, selection) => {
		switch ( selection ) {
			case '1rating': {
				handleStarSelect(d, 1);
				return;
			}
			case '2rating': {
				handleStarSelect(d, 2);
				return;
			}
			case '3rating': {
				handleStarSelect(d, 3);
				return;
			}
			case '4rating': {
				handleStarSelect(d, 4);
				return;
			}
			case '5rating': {
				handleStarSelect(d, 5);
				return;
			}
		}
	}



	const d = document.getElementById('start-rating')
	console.log(d);

	const rate_input = document.getElementById("id_rating");
	rate_input.value = 5;

	const c = d.children;
	for (let i = 0; i < c.length; i++){
		item = c[i];
		item.addEventListener('click', function (event) {
			id = event.target.id;
			handleSelect(d, id);
			rate_input.value = i+1;

		})

		item.addEventListener('mouseover', function (event) {
			id = event.target.id;
			handleSelect(d, id);
		})
	}

</script>

{% endblock %}

pythonProject/mysite/product/templates/product/test.html
{% extends 'product/base.html' %}


{% block content %}

<div class="test">This is Test</div>

	{% endblock %}